version: '3'

services:
  dbos:
   image: mysql:5.7
   volumes:
     - mysql_storage_new:/var/lib/mysql
   restart: always
   environment:
     MYSQL_ROOT_PASSWORD: rootpass
     MYSQL_USER: rohith
     MYSQL_PASSWORD: redhat
     MYSQL_DATABASE: mydb


  wordpressos:
    image: wordpress:5.1.1-php7.3-apache
    restart: always
    depends_on:
      - dbos
    ports:
      - 8082:80
    environment:
      WORDPRESS_DB_HOST: dbos
      WORDPRESS_DB_USER: rohith
      WORDPRESS_DB_PASSWORD: redhat
      WORDPRESS_DB_NAME: mydb
    volumes:
      - wp_storage_new:/var/www/html

  joomlaos:
    image: joomla:3.9.16-php7.2-apache
    restart: always
    depends_on:
      - dbos
    ports:
      - 8083:80
    environment:
      JOOMLA_DB_HOST: dbos:3306
      JOOMLA_DB_USER: rohith
      JOOMLA_DB_PASSWORD: redhat
      JOOMLA_DB_NAME: mydb
    volumes:
      - joomla_storage_new:/var/www/html



volumes:
   wp_storage_new:
   mysql_storage_new:
   joomla_storage_new:        
